// See LICENSE for license details.
// Oracles: FAMETransform clockMetadata, WriteXDCFile, XDCAnnotationConstants.
#include "goldengate/XDCEmission.h"
#include "goldengate/AnnotationClasses.h"
#include "circt/Support/InstanceGraph.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "mlir/IR/Builders.h"
#include "llvm/ADT/DenseSet.h"
#include <functional>
#include <limits>

using namespace mlir;
using namespace circt::firrtl;
namespace {
constexpr llvm::StringLiteral header =
    "# This file was generated by WriteXDCFile from collected XDCAnnotations.\n";
struct Reference {
  FModuleLike root;
  SmallVector<std::string> relative;
};

// Resolve imported reference spelling into FIRRTL modules, actual instances,
// typed ports/declarations and aggregate selectors. Text only survives at the
// final XDC boundary; it cannot select a nonexistent or ambiguous IR entity.
std::optional<Reference> resolveReference(CircuitOp circuit,
    circt::igraph::InstanceGraph &graph, StringRef target, std::string &error) {
  auto reject = [&](StringRef why)->std::optional<Reference> {
    error=why.str(); return std::nullopt;
  };
  if(!target.consume_front("~")) return reject("XDC target must start with '~'");
  auto [circuitName,local]=target.split('|');
  auto [hierarchy,ref]=local.split('>');
  if(circuitName!=circuit.getName()||hierarchy.empty()||ref.empty()||ref.contains('>'))
    return reject("XDC requires a reference in the current circuit");
  SmallVector<StringRef> path; hierarchy.split(path,'/');
  auto *node=graph.lookup(StringAttr::get(circuit.getContext(),path.front()));
  if(!node) return reject("XDC root module does not exist");
  Reference result{node->getModule<FModuleLike>(),{}};
  for(auto step:ArrayRef<StringRef>(path).drop_front()) {
    auto [name,module]=step.split(':');
    circt::igraph::InstanceRecord *found=nullptr;
    for(auto *record:*node) {
      auto instance=record->getInstance<InstanceOp>();
      if(instance&&instance.getName()==name) {
        if(found) return reject("XDC instance path is ambiguous");
        found=record;
      }
    }
    if(!found||module.empty()||found->getTarget()->getModule<FModuleLike>().getModuleName()!=module)
      return reject("XDC instance path does not match CIRCT hierarchy");
    result.relative.push_back(name.str()); node=found->getTarget();
  }
  SmallVector<StringRef> components;
  auto end=ref.find_first_of(".["); components.push_back(ref.take_front(end));
  ref=ref.drop_front(components.front().size());
  while(!ref.empty()) {
    if(ref.consume_front(".")) {
      auto end=ref.find_first_of(".[");auto component=ref.take_front(end);
      if(component.empty()) return reject("empty XDC field selector");
      components.push_back(component);ref=ref.drop_front(component.size());
    } else if(ref.consume_front("[")) {
      auto close=ref.find(']');
      if(close==StringRef::npos) return reject("unterminated XDC index selector");
      components.push_back(ref.take_front(close));ref=ref.drop_front(close+1);
    } else return reject("invalid XDC field selector");
  }
  auto module=node->getModule<FModuleLike>();
  Type type;unsigned matches=0;
  for(auto port:module.getPorts()) if(port.name.getValue()==components.front()) {
    type=port.type;++matches;
  }
  Operation *declaration=nullptr;
  if(auto internal=dyn_cast<FModuleOp>(module.getOperation()))
    internal.walk([&](Operation *op) {
      if(!isa<NodeOp,WireOp,RegOp,RegResetOp,MemOp,InstanceOp>(op)) return;
      auto name=op->getAttrOfType<StringAttr>("name");
      if(name&&name.getValue()==components.front()) {declaration=op;++matches;}
    });
  if(matches!=1) return reject("XDC reference is missing or ambiguous");
  unsigned firstField=1;
  if(auto instance=dyn_cast_or_null<InstanceOp>(declaration)) {
    if(components.size()<2) return reject("XDC instance reference needs a port");
    bool found=false;
    for(unsigned i=0;i<instance.getNumResults();++i)
      if(instance.getPortNameStr(i)==components[1]) {type=instance.getResult(i).getType();found=true;}
    if(!found) return reject("XDC instance port does not exist");
    firstField=2;
  } else if(declaration) type=declaration->getResult(0).getType();
  for(auto field:ArrayRef<StringRef>(components).drop_front(firstField)) {
    if(auto bundle=dyn_cast<BundleType>(type)) {
      auto element=bundle.getElement(field);
      if(!element) return reject("XDC bundle field does not exist");
      type=element->type;
    } else if(auto vector=dyn_cast<FVectorType>(type)) {
      unsigned index;
      if(field.getAsInteger(10,index)||index>=vector.getNumElements())
        return reject("XDC vector index does not exist");
      type=vector.getElementType();
    } else return reject("XDC selector applied to a ground value");
  }
  if(!type||isa<BundleType,FVectorType>(type)) return reject("XDC reference must select a ground value");
  for(auto component:components) result.relative.push_back(component.str());
  return result;
}
std::string joined(ArrayRef<std::string> components) {
  std::string result;
  for(auto [i,s]:llvm::enumerate(components)) {if(i) result+='/';result+=s;}
  return result;
}
} // namespace

LogicalResult goldengate::addFAMEClockConstraint(CircuitOp circuit,FModuleOp model,
    StringRef modelClockName,const RationalClockInfo &clock,std::string &error) {
  auto reject=[&](StringRef why){error=why.str();return failure();};
  auto raw=circuit->getAttrOfType<ArrayAttr>("rawAnnotations");
  if(!raw||!model||model->getParentOp()!=circuit.getOperation()||clock.name.empty()||
     !clock.mfmr||clock.mfmr>uint64_t(std::numeric_limits<int64_t>::max()))
    return reject("FAME clock XDC requires retained annotations and analyzed clock metadata");
  std::string gateName=(modelClockName+"_buffer").str(); InstanceOp gate;
  for(auto i:model.getOps<InstanceOp>()) if(i.getName()==gateName) {
    if(gate) return reject("FAME clock XDC gate is ambiguous");gate=i;
  }
  if(!gate||gate.getModuleName()!="AbstractClockGate"||gate.getNumResults()!=3||
     gate.getPortNameStr(2)!="O"||!isa<ClockType>(gate.getResult(2).getType()))
    return reject("FAME clock XDC requires the actual abstract gate output");
  if(gate->hasAttr("goldengate.generatedClockConstraint"))
    return reject("FAME clock constraint already exists");
  OpBuilder b(circuit.getContext());
  gate->setAttr("goldengate.generatedClockConstraint",b.getDictionaryAttr({
    b.getNamedAttr("name",b.getStringAttr(clock.name)),
    b.getNamedAttr("mfmr",b.getI64IntegerAttr(clock.mfmr))}));
  return success();
}

LogicalResult goldengate::prepareXDCOutput(CircuitOp circuit,std::string &error) {
  auto reject=[&](StringRef why){error=why.str();return failure();};
  auto raw=circuit->getAttrOfType<ArrayAttr>("rawAnnotations");
  if(!raw) return reject("XDC emission needs retained annotations");
  DictionaryAttr paths; SmallVector<DictionaryAttr> snippets;SmallVector<Attribute> retained;
  for(auto a:raw) {
    auto d=dyn_cast<DictionaryAttr>(a);auto cls=d?d.getAs<StringAttr>("class"):StringAttr();
    if(!cls) return reject("malformed retained annotation");
    if(cls.getValue()==AnnotationClasses::XDCPaths) {
      if(paths) return reject("XDC emission requires exactly one circuit path annotation");paths=d;
    } else if(cls.getValue()==AnnotationClasses::InternalXDC) snippets.push_back(d);
    else {
      if(cls.getValue()==AnnotationClasses::XDCOutput) return reject("XDC output already exists");
      if(cls.getValue()==AnnotationClasses::OutputFile) {
        auto suffix=d.getAs<StringAttr>("fileSuffix");
        if(suffix&&(suffix.getValue()==".synthesis.xdc"||suffix.getValue()==".implementation.xdc"))
          return reject("XDC output filename already selected");
      }
      retained.push_back(a);
    }
  }
  if(!paths) return reject("XDC emission requires exactly one circuit path annotation");
  for(auto name:{"preLinkPath","postLinkPath"})
    if(paths.get(name)&&!paths.getAs<StringAttr>(name)) return reject("invalid XDC circuit path");
  circt::firrtl::InstanceGraph graph(circuit);
  auto *top=graph.lookup(StringAttr::get(circuit.getContext(),circuit.getName()));
  if(!top||!top->noUses()) return reject("invalid XDC circuit top");
  llvm::DenseSet<circt::igraph::InstanceGraphNode *> active,visited;
  std::function<bool(circt::igraph::InstanceGraphNode *)> acyclic=[&](auto *node) {
    if(active.count(node)) return false;if(!visited.insert(node).second) return true;
    active.insert(node);for(auto *record:*node) if(!acyclic(record->getTarget())) return false;
    active.erase(node);return true;
  };
  for(auto *node:graph) if(!acyclic(node)) return reject("recursive XDC hierarchy");
  circt::igraph::InstancePathCache cache(graph);
  // Generated-clock metadata lives on the actual gate operation so module
  // renaming and wrapper insertion cannot detach it from the output pin.
  // Lower FPGA-specific text here, after the final hierarchy is available.
  bool invalidClock=false;
  OpBuilder builder(circuit.getContext());
  circuit.walk([&](InstanceOp gate) {
    auto attr=gate->getAttr("goldengate.generatedClockConstraint");
    if(!attr) return;
    auto metadata=dyn_cast<DictionaryAttr>(attr);
    auto name=metadata?metadata.getAs<StringAttr>("name"):StringAttr();
    auto mfmr=metadata?metadata.getAs<IntegerAttr>("mfmr"):IntegerAttr();
    auto model=gate->getParentOfType<FModuleOp>();
    if(!name||name.getValue().empty()||!mfmr||mfmr.getInt()<1||!model||
       gate.getNumResults()!=3||gate.getPortNameStr(2)!="O"||
       !isa<ClockType>(gate.getResult(2).getType())) {invalidClock=true;return;}
    std::string target="~"+circuit.getName().str()+"|"+model.getName().str()+">"+gate.getName().str()+".O";
    std::string clockName=name.getValue().str();
    std::string body="create_generated_clock -name "+clockName+
      " -source [get_pins -of [get_clocks host_clock]] [get_pins -hierarchical -regexp .*{}.*] -divide_by 1\n"+
      "set_multicycle_path "+std::to_string(mfmr.getInt())+" -setup -from [get_clocks "+clockName+
      "] -to [get_clocks "+clockName+"]\nset_multicycle_path "+std::to_string(mfmr.getInt()-1)+
      " -hold  -from [get_clocks "+clockName+"] -to [get_clocks "+clockName+"]\n";
    snippets.push_back(builder.getDictionaryAttr({
      builder.getNamedAttr("destinationFile",builder.getDictionaryAttr({builder.getNamedAttr("class",builder.getStringAttr(AnnotationClasses::XDCImplementation))})),
      builder.getNamedAttr("formatString",builder.getStringAttr(body)),
      builder.getNamedAttr("argumentList",builder.getArrayAttr({builder.getStringAttr(target)}))}));
  });
  if(invalidClock) return reject("malformed generated clock metadata");
  std::string bodies[2]={header.str(),header.str()};
  for(auto snippet:snippets) {
    auto destination=snippet.getAs<DictionaryAttr>("destinationFile");
    auto cls=destination?destination.getAs<StringAttr>("class"):StringAttr();
    auto format=snippet.getAs<StringAttr>("formatString");
    auto arguments=snippet.getAs<ArrayAttr>("argumentList");
    if(!cls||!format||!arguments) return reject("malformed internal XDC annotation");
    unsigned index;
    if(cls.getValue()==AnnotationClasses::XDCSynthesis) index=0;
    else if(cls.getValue()==AnnotationClasses::XDCImplementation) index=1;
    else return reject("unsupported XDC destination");
    SmallVector<Reference> references;
    for(auto a:arguments) {
      auto target=dyn_cast<StringAttr>(a);
      if(!target) return reject("XDC argument is not a reference target");
      auto resolved=resolveReference(circuit,graph,target.getValue(),error);
      if(!resolved) return failure();
      if(!references.empty()&&references.front().root!=resolved->root)
        return reject("XDC arguments must have a common explicit root module");
      references.push_back(std::move(*resolved));
    }
    SmallVector<StringRef> segments;format.getValue().split(segments,"{}",-1,true);
    // Java regex split used by SFC discards trailing empty segments.
    if(!format.getValue().empty()) while(!segments.empty()&&segments.back().empty()) segments.pop_back();
    auto serialize=[&](const circt::igraph::InstancePath *instancePath) {
      SmallVector<std::string> formatted;
      for(auto &reference:references) {
        SmallVector<std::string> full;
        if(auto prefix=paths.getAs<StringAttr>(index?"postLinkPath":"preLinkPath")) full.push_back(prefix.getValue().str());
        if(instancePath) for(auto i:*instancePath) full.push_back(cast<InstanceOp>(i.getOperation()).getName().str());
        full.append(reference.relative.begin(),reference.relative.end());formatted.push_back(joined(full));
      }
      std::string output;
      for(unsigned i=0;i<std::max(segments.size(),formatted.size());++i) {
        if(i<segments.size()) output+=segments[i].str();if(i<formatted.size()) output+=formatted[i];
      }
      bodies[index]+='\n';bodies[index]+=output;
    };
    if(references.empty()) serialize(nullptr); // zero-argument snippet emitted once
    else for(auto path:cache.getAbsolutePaths(references.front().root,top)) serialize(&path);
  }
  OpBuilder b(circuit.getContext());SmallVector<Attribute> updated;
  for(unsigned i=0;i<2;++i) updated.push_back(b.getDictionaryAttr({
    b.getNamedAttr("class",b.getStringAttr(AnnotationClasses::XDCOutput)),
    b.getNamedAttr("fileBody",b.getStringAttr(bodies[i])),
    b.getNamedAttr("suffix",b.getStringAttr(i?".implementation.xdc":".synthesis.xdc"))}));
  updated.append(retained.begin(),retained.end());circuit->setAttr("rawAnnotations",b.getArrayAttr(updated));
  return success();
}
